// Generate tests/fixtures/day-counters.sexp from QuantLib.
//
//   nix develop .#fixtures -c sh tests/fixtures/generate.sh
//
// Each fixture is a Lisp list
//
//   ("convention" "START" "END" day-count year-fraction)
//
// with START <= END. Reversed pairs are not generated: fincl makes every
// convention antisymmetric, which QuantLib's 30/360 is not.

#include <ql/quantlib.hpp>
#include <ql/version.hpp>

#include <algorithm>
#include <cstdio>
#include <random>
#include <set>
#include <string>
#include <utility>
#include <vector>

using namespace QuantLib;

namespace {

std::vector<Date> edgeDates() {
    // Month ends, the 30th and 31st, February 28/29 and year boundaries,
    // around ordinary, leap and century years.
    std::set<Date> dates;
    for (Year y : {1999, 2000, 2001, 2023, 2024, 2025, 2099, 2100, 2101}) {
        for (int m = 1; m <= 12; ++m) {
            Day last = Date::endOfMonth(Date(1, Month(m), y)).dayOfMonth();
            for (Day d : {1, 15, 28, 29, 30, 31, int(last)})
                if (d <= last)
                    dates.insert(Date(d, Month(m), y));
        }
    }
    return {dates.begin(), dates.end()};
}

std::vector<std::pair<Date, Date>> pairs() {
    std::mt19937_64 rng(20260924);
    std::vector<Date> edges = edgeDates();
    std::vector<std::pair<Date, Date>> out;
    // Each edge date against up to 12 later edge dates within 3 years.
    for (std::size_t i = 0; i < edges.size(); ++i) {
        std::vector<Date> later;
        for (std::size_t j = i; j < edges.size(); ++j)
            if (edges[j] - edges[i] <= 3 * 366)
                later.push_back(edges[j]);
        std::shuffle(later.begin(), later.end(), rng);
        for (std::size_t k = 0; k < std::min<std::size_t>(12, later.size()); ++k)
            out.emplace_back(edges[i], later[k]);
    }
    // Equal dates.
    for (std::size_t i = 0; i < edges.size(); i += 10)
        out.emplace_back(edges[i], edges[i]);
    // Random pairs, spans up to 40 years.
    const auto lo = Date(1, January, 1901).serialNumber();
    const auto hi = Date(31, December, 2150).serialNumber();
    std::uniform_int_distribution<Date::serial_type> start(lo, hi);
    std::uniform_int_distribution<Date::serial_type> span(0, 40 * 365);
    for (int i = 0; i < 600; ++i) {
        auto a = start(rng);
        auto b = std::min(hi, a + span(rng));
        out.emplace_back(Date(a), Date(b));
    }
    return out;
}

std::string iso(const Date& d) {
    char buf[16];
    std::snprintf(buf, sizeof buf, "%04d-%02d-%02d", int(d.year()), int(d.month()),
                  int(d.dayOfMonth()));
    return buf;
}

std::string lispDouble(double x) {
    // 17 significant digits read back to the same double.
    char buf[64];
    std::snprintf(buf, sizeof buf, "%.17g", x);
    std::string s = buf;
    auto e = s.find('e');
    if (e != std::string::npos)
        s[e] = 'd';
    else
        s += "d0";
    return s;
}

} // namespace

int main(int argc, char* argv[]) {
    if (argc != 2) {
        std::fprintf(stderr, "usage: %s OUTPUT\n", argv[0]);
        return 2;
    }
    const std::vector<std::pair<std::string, DayCounter>> conventions = {
        {"actual-360", Actual360()},
        {"actual-365-fixed", Actual365Fixed()},
        {"thirty-360-bond-basis", Thirty360(Thirty360::BondBasis)},
        {"thirty-360-european", Thirty360(Thirty360::European)},
        {"actual-actual-isda", ActualActual(ActualActual::ISDA)},
        {"business-252-weekends-only", Business252(WeekendsOnly())},
    };
    const auto ps = pairs();
    std::FILE* f = std::fopen(argv[1], "w");
    if (!f) {
        std::perror(argv[1]);
        return 1;
    }
    std::fprintf(f, ";;;; Generated by generate_day_counters.cpp. Do not edit.\n");
    std::fprintf(f, "(:quantlib-version \"%s\")\n", QL_VERSION);
    for (const auto& [name, dc] : conventions)
        for (const auto& [a, b] : ps)
            std::fprintf(f, "(\"%s\" \"%s\" \"%s\" %ld %s)\n", name.c_str(),
                         iso(a).c_str(), iso(b).c_str(), long(dc.dayCount(a, b)),
                         lispDouble(dc.yearFraction(a, b)).c_str());
    std::fclose(f);
    std::printf("wrote %zu fixtures to %s\n", ps.size() * conventions.size(), argv[1]);
    return 0;
}
