;;;; golden.sexp --- generated by tests/fixtures/make-golden.lisp
;;;; Entries: (name price standard-error [:tolerance x]). Add a :tolerance by
;;;; hand only when a task allows a round-off change, with a comment saying why.

("mc european gbm, antithetic" 10.534049230014624d0 0.047153203157626035d0)
("mc european gbm, no antithetic" 10.507977424495616d0 0.06637511221668252d0)
("mc european gbm, inverse transform" 10.521580580739961d0 0.046784892870282d0)
("mc european gbm, pcg stream" 10.360163033837523d0 0.04645861770836071d0)
;; Task 06 phase 2: stepped Europeans stream terminal payoffs per chunk and
;; pool the chunk accumulators instead of reducing one array of all paths.
;; Same paths, different summation order: moves ~1e-14 relative.
("mc european heston, stepped" 10.220905321477373d0 0.07830421498835334d0 :tolerance 1d-13)
("mc european cev, stepped" 10.48426026356424d0 0.1009543514807696d0 :tolerance 1d-13)
("mc american gbm, lsm" 4.487464400609813d0 0.02104872655288929d0)
("mc american heston, lsm" 4.08803985443738d0 0.014317435283169717d0)
("binomial american put, bbsr" 14.804493936664647d0 NIL)
("binomial american put, bbs" 14.805631483783706d0 NIL)
("binomial american put, crr" 14.8051140021255d0 NIL)
("binomial american call, bbsr" 15.918041943331751d0 NIL)
("binomial bermudan put, bbsr" 8.804118464559181d0 NIL)
("binomial bermudan put, crr" 8.801648022417876d0 NIL)
("cos european gbm" 10.450583572185586d0 NIL)
("cos european heston" 10.15462703008175d0 NIL)
("cos bermudan gbm put" 8.804265380232513d0 NIL)
("cos american gbm put" 14.804436122779702d0 NIL)
("cos american gbm call" 15.918021425816217d0 NIL)
("black-scholes european" 10.450583572185579d0 NIL)
("baw american put" 14.78972095489883d0 NIL)
